# Generated by Django 4.2.6 on 2023-10-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='pic',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='hit_flop',
            field=models.BooleanField(default='images/no-image.png'),
        ),
    ]
