# Generated by Django 4.2.6 on 2023-10-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_movie_pic_alter_movie_hit_flop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='hit_flop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='pic',
            field=models.ImageField(upload_to='images'),
        ),
    ]
