# Generated by Django 4.2.6 on 2023-10-06 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_movie_hit_flop_alter_movie_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('actor_name', models.CharField(max_length=50)),
                ('actress_name', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=256)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.movie')),
            ],
        ),
    ]
